cluster.name: mycluster
node.name: "master"
node.master: true
node.data: true
index.number_of_shards: 5
index.number_of_replicas: 0
discovery.zen.ping.multicast.enabled: true
# discovery.zen.ping.unicast.hosts: ["localhost"]
